### ISSUE TITLE
wish: provide differences with Run.js

### ISSUE THREAD

**Issue by markstos** [pawelgalazka/tasksfile#100]
Tasksfile is now considered in "Beta", which is a public-feedback stage.

I'm a contributor and user that is interested in providing pre-release feedback, but it's difficult to know what has changed besides the name. 

A simple changelog that provides a list of changes in each release would be helpful to know where to focus attention.

Thanks.

**Comment by pawelgalazka** [comment]
Changelog draft: https://github.com/pawelgalazka/tasksfile/blob/master/CHANGELOG.md#500-beta

**Comment by markstos** [comment]
Thanks. The changes look OK, but not compelling enough for us to upgrade immediately. I think we'll stick with Run.js 4.4 for a while.

**Comment by pawelgalazka** [comment]
@markstos I would recommend the same. Currently `tasksfile` beta api won't change so it will stay the same. The only thing which will change is the engine of handling `cli`, which will use updated version of https://github.com/pawelgalazka/cli. `tasksfile` will come out of beta when this transition will be finished and well tested.
