### ISSUE TITLE
Add a way to retrieve raw args from options

### ISSUE THREAD

**Issue by dorian-marchal** [pawelgalazka/tasksfile#101]
Sometimes, I need to directly forward arguments to a command without knowing them beforehand.

For example, I would want to do that:

```js
test(options, ...args) {
  sh(`NODE_ENV=testing jest ${options.raw.join(' ')} ${args.join(' ')}`);
},
```

```sh
npm run test --watch pattern
```

Is their a way to do that without reconstructing raw params from options and args?

**Comment by pawelgalazka** [comment]
Without reconstructing params it's not currently possible but I think about introducing that option in future versions. Raw args and options may be available under `options['--']`

**Comment by dorian-marchal** [comment]
For now, I use `process.argv` but I imagine it can break in some circumstances:

```js
const extraArgs = process.argv.slice(3).join(' ');

// ...

test() {
  sh(`NODE_ENV=testing jest ${extraArgs}`);
},
```

**Comment by pawelgalazka** [comment]
It's done: https://github.com/pawelgalazka/tasksfile#rawargs
`rawArgs()` function is available now

**Comment by dorian-marchal** [comment]
Thanks :+1:
