### ISSUE TITLE
Synchronous sh command errors

### ISSUE THREAD

**Issue by possibleworlds** [pawelgalazka/tasksfile#103]
Hi! Feel I am missing something simple... how you do you get synchronous shell command errors to print to console. If an async command fails the correct error is printed, but if it is synchronous you get a ShellError: Command failed without any info passed from the script.

**Comment by muntasirsyed** [comment]
Most likely cause: https://github.com/pawelgalazka/tasksfile/commit/cfe9410da4602718ab3870ecf41ff324c2ba4f5b

**Comment by ghost** [comment]
Bump. If this isn't an actual issue, then it's at least a bit unclear from the README.

**Comment by ljani** [comment]
As a workaround is to set `nopipe` to true:

```js
sh("myfailingcommand", {
    nopipe: true,
    async: false
});
```

[This will change `stdio` to `["inherit", "inherit", "inherit"]`](https://github.com/pawelgalazka/shell/blob/808e21506f4395389a67dfa6df51948db4f25c05/src/index.ts#L147-L151).
