### ISSUE TITLE
Yarn audit : 1 vulnerability found

### ISSUE THREAD

**Issue by misteravo** [pawelgalazka/tasksfile#106]
$ yarn audit
yarn audit v1.19.1
│ high          │ Prototype Pollution 
│ Package       │ lodash 
│ Patched in    │ >=4.17.12 
│ Dependency of │ tasksfile   
│ Path          │ tasksfile > @pawelgalazka/cli > lodash  
│ More info     │ https://www.npmjs.com/advisories/1065 

1 vulnerabilities found - Packages audited: 905558
Severity: 1 High
Done in 1.98s.

**Comment by pawelgalazka** [comment]
done
