### ISSUE TITLE
Renaming project to: Taskfile

### ISSUE THREAD

**Issue by pawelgalazka** [pawelgalazka/tasksfile#94]
Lately I started wondering about renaming the project.

I have couple reasons **why**:

- junior developers / developers often confuse `npx run` with `npm run`, thinking it's kind of built in in npm feature and start to wonder in general how this relates to `npm scripts`. Situation starts to confuse more with `yarn`. Like what `yarn run` do with `runjs`, is it calling `runjs` or `npm scripts`. So they are lost to what actually happens and what actually gets called.

- so, it would be good to make a clear separation from `npm scripts`

- in practice I noticed developers saying `runfile` more in relation to `runjs` than `runjs`, `runjs` seems too general, less specific

- new devs are lost to how tasks are called, looking for stuff in npm scripts first where there is no any

**Proposition**:

- keep one name for project and for file which it will be using: `taskfile`
- place taskfile binary in npm scripts, like: `task: "task"`
- call tasks through `yarn task arg1 arg2` or `npm run task arg1 arg2`
- package will be installed by `npm install --save-dev @pawelgalazka/taskfile`

**Benefits**:
- taskfile is referenced in npm scripts, so it's easier to track what's happening
- we use different name than npm scripts, so it's easier to differentiate from it
- project name is the same as the main file which is using, less confusion about naming in practice

**Comment by pawelgalazka** [comment]
Project has been renamed to `Tasksfile` not `Taskfile`

**Comment by markstos** [comment]
There's also another project that is named "runjs" now, but is completely different.
