### ISSUE TITLE
Support only async shell call

### ISSUE THREAD

**Issue by pawelgalazka** [pawelgalazka/tasksfile#96]
Considering that we have `async` and `await`, seems that there is no need for `sync` version of `run`, as we could have always `async` version and use `await` eventually if we want to make it sync:

```js
await sh('command 1')
await sh('command 2')
```

*Benefits*:
- stop switching between `spawn` and `execSync` internally
- passing options to `spawn` will be cleaner as we don't have to deal with slightly different `execSync` api

**Comment by markstos** [comment]
This would be OK with me.

**Comment by pawelgalazka** [comment]
Shell function does not belong to this repo anymore, closing
