### ISSUE TITLE
Published package v4.4.1 breaks API

### ISSUE THREAD

**Issue by mszczepanczyk** [pawelgalazka/tasksfile#99]
Hey! The new version introduces these type declarations:

```ts
export declare function run(command: string, options: IOptions & {
    async: true;
}, logger?: Logger): Promise<string | null>;
export declare function run(command: string, options: IOptions & {
    async?: false | null;
}, logger?: Logger): string | null;
```

rendering `options` arg mandatory.

I can see this is already fixed in `master` and I'd consider publishing the new package ASAP because the current state of things breaks builds for anyone using latest version or **any 4.\* version with caret prefix**. It broke mine :). Thanks!

**Comment by pawelgalazka** [comment]
Hey, thanks for feedback!
4.4.2 version is published with fixed `TypeScript` type for `run` function.
